### ISSUE TITLE
Mobile theme issues

### ISSUE THREAD

**Issue by arunoda** [kadirahq/getstorybook.io#24]
There are some issues when the site is watching on mobile. 

![img_0523](https://cloud.githubusercontent.com/assets/50838/18115214/213b96d2-6f5b-11e6-96c4-7c795c180cae.PNG)

Check these featured storybook link texts. They are colored. We need to make them as black. (Original color)

See:

![img_0524](https://cloud.githubusercontent.com/assets/50838/18115252/865f4202-6f5b-11e6-82dd-10f43da32e38.PNG)

Add some space between header logo and the links. It's hard to click correctly on mobile.

**Comment by thinkholic** [comment]
Fixed with #25
