### ISSUE TITLE
Fix docs links

### ISSUE THREAD

**Issue by mnmtanish** [kadirahq/getstorybook.io#51]
Fix links in these lines:

 - https://github.com/fdaciuk/getstorybook.io/blob/311e152db5608a1da06bde8322a78caf6cb5b121/src/docs/storybook-hub/management-features/env-variables.js#L10
 - https://github.com/fdaciuk/getstorybook.io/blob/311e152db5608a1da06bde8322a78caf6cb5b121/src/docs/react-storybook/configurations/env-vars.js#L28

**Comment by fdaciuk** [comment]
Doing @mnmtanish =)

**Comment by mnmtanish** [comment]
Awesome! and thanks :)

**Comment by fdaciuk** [comment]
\o/ :dancer: :dancer: :sparkles:
